apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-techdocaction-oct29 
  janus-idp.io/tekton: test-techdocaction-oct29
  backstage.io/kubernetes-id: test-techdocaction-oct29
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-techdocaction-oct29
resources: 
- application-dev.yaml